repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.2.7
    hooks:
      - id: gitleaks
        args: ["--config", ".github/config/.gitleaks.toml", "--verbose"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.21.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
