---
extends: default
ignore: node_modules
rules:
  new-lines: disable
  line-length:
    max: 300
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments-indentation: disable
  truthy:
    check-keys: false
